//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatHang_ChiTiet
    {
        public int ID { get; set; }
        public Nullable<int> DatHang_ID { get; set; }
        public Nullable<int> Sach_ID { get; set; }
        public Nullable<short> SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        public virtual DatHang DatHang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
